### ISSUE TITLE
Can patch application respect preserve-paths?

### ISSUE THREAD

**Issue by rohnjeynolds** [cweagans/composer-patches#116] opened 2017-03-09 16:41 UTC
The problem I'm encountering might be too specific. I used DrupalComposer to create Drupal 7 project, which includes preserve-paths (https://github.com/derhasi/composer-preserve-paths) as a dependency. The Drupal root is /web/, and I have custom code in /web/sites/all/modules/custom, which I name in composer.json as a path to be preserved, and I version-control this folder. 

If I use composer-patches to apply a Drupal core patch, the first thing that happens is the project is deleted and reinstalled so it can be patched. But in this case, the project is drupal/drupal and the location is /web/, so the entire Drupal root gets deleted, including my /web/sites/ folder and custom code. (See output below.)

Is it possible to make this package respect preserve-paths somehow?

And, by the way, thank you tons for this package. This issue nothwithstanding, this is magical when it comes to managing patches to contributed Drupal modules.

``` $ composer update
Gathering patches for root package.
Removing package drupal/drupal so that it can be re-installed and re-patched.
Deleting web/ - deleted
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
Gathering patches for root package.
  - Installing drupal/drupal (7.54.0): Gathering patches for dependencies. This might take a minute.
Loading from cache
  - Applying patches for drupal/drupal
    https://www.drupal.org/files/issues/add_a_startup-1543858-30.patch (Add startup configuration for PHP server)

Writing lock file
Generating autoload files
```

**Comment by SebCorbin** [comment] 2017-03-14 15:50
Duplicate of #42

**Comment by cweagans** [comment] 2017-03-29 21:41
Yep, duplicate. I want to add support for this, but still kind of stuck on a good way to do it. @SebCorbin has done some work on this, but I haven't had a chance to look just yet.

**Closed by cweagans** 2017-03-29 21:41 UTC
