### ISSUE TITLE
Composer update drupal/some_module updates all packages where patches modified in composer.json

### ISSUE THREAD

**Issue by jonathanjfshaw** [cweagans/composer-patches#121] opened 2017-04-19 13:22 UTC
This is probably related to #12 in some way.
I add/modify 2 patches in composer.json for 2 different packages. I try to run composer update for 1 package, but both get updated.

**Comment by CRYX2** [comment] 2017-05-18 08:03
Same problem... any ides how to solve?

**Comment by cweagans** [comment] 2018-06-02 06:50
Dupe of https://github.com/cweagans/composer-patches/issues/126 and has some overlap with https://github.com/cweagans/composer-patches/issues/135- if the packages don't get removed, they won't get reinstalled. If you're just operating on one package, that should be the only thing that gets removed, reinstalled, and repatched.

**Closed by cweagans** 2018-06-02 06:50 UTC
