### ISSUE TITLE
PHP 8.2 Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by sc0rp10** [cweagans/composer-patches#427] opened 2022-12-15 22:51 UTC
Hello! Just ran composer install on my fresh PHP 8.2 installation and got an error

```
Deprecation Notice: Creation of dynamic property cweagans\Composer\Patches::$installedPatches is deprecated in /Volumes/dev/profile/new/vendor/cweagans/composer-patches/src/Patches.php:63
```

**Comment by danepowell** [comment] 2022-12-16 18:43
Would be fixed by https://github.com/cweagans/composer-patches/pull/422

**Comment by sc0rp10** [comment] 2022-12-16 18:49
ah, got it thanks!

**Comment by andypost** [comment] 2022-12-16 23:39
Duplicate of https://github.com/cweagans/composer-patches/pull/409

**Closed** 2022-12-20 22:54 UTC

**Comment by back-2-95** [comment] 2022-12-21 09:22
New release is needed to get it to the Packagist
