### ISSUE TITLE
Patching core modules as ckeditor

### ISSUE THREAD

**Issue by boesbo** [cweagans/composer-patches#58] opened 2016-07-20 06:50 UTC
I do not understand how to patch ckeditor.
I did:
`"patches": {
            "drupal/ckeditor": {
                "patches-file": "patches/ckeditor.patch"
            }
        }`
but it does not work
(good job)

**Comment by cweagans** [comment] 2016-07-20 15:54
@boesbo Can you please supply your complete composer.json? If you don't want to post it publicly, feel free to email it to me@cweagans.net.

**Comment by boesbo** [comment] 2016-07-20 15:59
Send now :)

**Comment by cweagans** [comment] 2016-07-20 16:09
Alrighty, so a couple things:

* Since `ckeditor` is bundled with Drupal, you actually want to patch `drupal/drupal` or `drupal/core`. Composer doesn't see the ckeditor module that ships with core as a separate package.
* You can either declare your patches in your `composer.json` *or* have an external patches file. If you have patches in your composer.json, it should look like this:

```
"extra": {
        "patches": {
            "drupal/drupal": {
                "Description of your patch": "location/of/your.patch"
            }
        }
    },
```

Note that the patch location can either be a local file with a path relative to your composer.json, or it can be a remote URL (HTTP/HTTPS/FTP/etc) that the plugin will fetch for you.

If you want to have a patches file, your root composer.json should look like this:

```
"extra": {
        "patches-file": "path/to/your/patches.json"
    },
```

And then your patches file would be something like this:

```
        {
            "drupal/drupal": {
                "Description of your patch": "location/of/your.patch"
            }
        }
```

**Comment by cweagans** [comment] 2016-07-20 16:10
In any case, the package that you're pointing at is incorrect, so nothing would get applied.

**Comment by boesbo** [comment] 2016-07-21 07:32
i try this:
`"extra": {
        "patches": {
            "drupal/drupal": {
                "Description of your patch": "location/of/your.patch"
            }
        }
    },`

The patch begins:
`diff --git a/modules/ckeditor/js/plugins/drupalimage/plugin.js b/modules/ckeditor/js/plugins/drupalimage/plugin.js
index 0025664..e04b1fb 100644
--- a/modules/ckeditor/js/plugins/drupalimage/plugin.js
+++ b/modules/ckeditor/js/plugins/drupalimage/plugin.js`

but, don't work :(

**Comment by cweagans** [comment] 2016-07-21 14:43
Two possible solutions:

1. Change your patch to start with:

```
diff --git a/core/modules/ckeditor/js/plugins/drupalimage/plugin.js b/core/modules/ckeditor/js/plugins/drupalimage/plugin.js index 0025664..e04b1fb 100644 --- a/core/modules/ckeditor/js/plugins/drupalimage/plugin.js +++ b/core/modules/ckeditor/js/plugins/drupalimage/plugin.js
```

(note the extra `core/` at the beginning of the paths). This is the format that core patches would be if you downloaded them from Drupal.org, so these should be suitable for patching `drupal/drupal`.

or

2. Switch to the Drupal Composer template (https://github.com/drupal-composer/drupal-project). This creates a scaffolding for your project that uses `drupal/core` instead of `drupal/drupal`. This would get your patch to apply correctly.

**Comment by boesbo** [comment] 2016-07-21 15:50
I modified the patch.
If I apply the patch like this:
`patch core/modules/ckeditor/js/plugins/drupalimage/plugin.js < profiles/finder_profile/patches/ckeditor.patch`
everything works

but if user composer:
`"extra": {
        "patches": {
            "drupal/drupal": {
                "patches-file": "profiles/finder_profile/patches/ckeditor.patch"
            }`

nothing is happening:
`Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Drupal\Core\Composer\Composer::preAutoloadDump
Drupal\Core\Composer\Composer::ensureHtaccess
`

**Comment by cweagans** [comment] 2018-06-02 07:09
I wasn't ever able to reproduce this, so closing. Please reopen if there is still a problem.

**Closed by cweagans** 2018-06-02 07:09 UTC
