### ISSUE TITLE
A patch with all new files & directories creates with a b/ prefix

### ISSUE THREAD

**Issue by pwolanin** [cweagans/composer-patches#199] opened 2018-03-20 19:05 UTC
Seeing this with version 1.6.4

I have a path for a contrib module:

Config schema #2918157
Source: https://www.drupal.org/files/issues/entity-reference-uuid-schema.patch

when this patch is applied the files end up nested an extra level in a b/ subdirectory.

Possibly this is because all the files and directories are new, so the patch can apply while creating the directory and -p0?

**Comment by pwolanin** [comment] 2018-03-20 19:14
Correction - the patch was committed by the maintainer, so -p1 doesn't apply but -p0 does by making the b/ directory

**Comment by mdonadio** [comment] 2018-03-29 17:05
Seeing this too.  Believe it is this dependency, https://github.com/contentacms/contenta_jsonapi, which specific this patch, https://www.drupal.org/files/issues/drupal-n2788777-105.patch

**Comment by solariel** [comment] 2018-04-16 12:35
Same problem with https://www.drupal.org/files/issues/2570593-30.patch
all new files are created twice.

![image](https://user-images.githubusercontent.com/10187877/38809320-cdaac4e8-418b-11e8-83e9-8fa407ac3e84.png)

**Comment by ixisandyr** [comment] 2018-04-24 14:15
Could be a duplicate of #43

**Comment by cweagans** [comment] 2018-06-02 06:35
Dupe of #43.

**Closed by cweagans** 2018-06-02 06:35 UTC
